# -*- coding: utf-8 -*-
"""AIML-Python programing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o25gmfydiE-Wo28SKmYTqzhqGLB990jA
"""

print('Hello world')
print('Hello')

print("print('Hello world')")

name = 'R.Rishi SriCharan'
rollnumber = 2420030638
branch = 'CSE'
print(name)
print(rollnumber)
print(branch)
print(type(name)) #function to check the data type of the given data print(type(VARIABLE))
print(type(rollnumber))
print(type(branch))

name= input('Enter your name..')
rollnumber= input('Enter your rollnumber')
branch= input('Enter your branch')
print('Your details are :-' , name, ',',rollnumber,',',branch)

#write program for addition, subtraction, division, multipilcation
a=int(input( 'Enter the value of a '))
b=int(input( 'Enter the value of b '))
addition= a+b
subtraction= a-b
multiplication= a*b
division = a/b
print(addition )
print(subtraction)
print(multiplication)
print(division )

print("addition of 10 and 20 is", 10+20)

#even or odd programs
a= int(input('Enter the value of a '))

if a%2 == 0:
  print("Even")
else:
  print("ODD")

n1=30
n2=20
print("Division of", n1,"and", n2,"is", n1/n2)

a,b,c=10,20,30
print(a,b,c)

"""Control Structures:-

conditional statements

*   iterative or looping
*   conditional


*   if
*   switch--not

itertive

for, while , do-while


indentation,

if condition:
"""

if 5>2:
  print("true")

a=33
b=33
if b>a :
  print("b is greater than a")
elif a==b:
    print("a and b are qual")

#biggest of three numbers
a=int(input("Enter the value of a: "))
b=int(input("Enter the value of b: "))
c=int(input("Enter the value of c: "))
if a>b and a>c:
  print("a is the greatest")
if b>a and b>c:
  print("b id the greatest")
else:
#elif c>a and c>b:
    print("c is the greatest")

#dispaly the even numbers between four hundred and five hundred using  for loop
for x in range( 400, 500):
 if x % 2 == 0:
  print(x)